// Warp (Epic D.1): parametric preset deformation — arc, bulge, flag, fisheye — applied over
// the selection's COMBINED bounding box, as one `<g data-hv-warp='{"type","amount","items","bbox"}'>`
// (the blend/repeat/width pattern): `items` holds each shape's ORIGINAL (undeformed) absolute
// path `d` + paint; children are regenerated by sampling each path to points, mapping every
// point through the preset's coordinate function, and refitting — a smooth bezier via
// hv/fitcurve.js's fitLoop for CLOSED subpaths (the same curve-fit the trace pipeline already
// uses), a plain polyline for OPEN ones (fitLoop is loop-only, and a straight line rarely wants
// smoothing anyway). Editing type/amount regenerates; Expand just drops the spec — the children
// are already real geometry, same as blend. Object.assign MIXIN — `this===editor`.
//
// Gradient mesh (D.4) and cage-based envelope distort (D.2/D.3) are deliberately NOT here —
// D.4 has no clean SVG primitive (flagged research-gated in the backlog) and D.2/D.3 need a
// whole interactive drag-handle UI on the scale of the width tool's profile editor. This ships
// the well-scoped, self-contained third: pick a preset, drag one amount, done.
import { SVG_NS, shapeToAbsPath, flattenSubpaths, nfmt } from "../../hv/index.js";
import { fitLoop, cubicsToPath } from "../../hv/fitcurve.js";
import { setStatus } from "../../app.js";

// x, y in [0,1] (bbox-relative); amount in [-1,1]. Returns the warped {x,y}, also [0,1]-relative.
const WARP_FNS = {
  arc: (x, y, a) => ({ x, y: y - a * 0.5 * Math.sin(Math.PI * x) }),
  bulge: (x, y, a) => {
    const dx = x - 0.5, dy = y - 0.5, r = Math.hypot(dx, dy), maxR = Math.hypot(0.5, 0.5);
    const t = Math.min(r / maxR, 1), push = a * 0.35 * Math.sin(Math.PI * t);
    const s = r > 1e-6 ? (r + push) / r : 1;
    return { x: 0.5 + dx * s, y: 0.5 + dy * s };
  },
  flag: (x, y, a) => ({ x, y: y + a * 0.18 * Math.sin(3 * Math.PI * x) }),
  fisheye: (x, y, a) => {
    const dx = x - 0.5, dy = y - 0.5, r = Math.hypot(dx, dy), maxR = Math.hypot(0.5, 0.5) || 1;
    const t = Math.min(r / maxR, 1), k = 1 + a * 1.8;
    const s = t > 1e-6 ? Math.pow(t, 1 / k) / t : 1;   // classic lens power-law remap (pinned at the rim)
    return { x: 0.5 + dx * s, y: 0.5 + dy * s };
  },
};
export const WARP_TYPES = Object.keys(WARP_FNS);
// [label, why] — same contract as actions.js's TOOL_WHY/VERB_WHY: a name and what it's FOR.
export const WARP_LABELS = { arc: "Arc", bulge: "Bulge", flag: "Flag", fisheye: "Fisheye" };
export const WARP_WHY = {
  arc: "Bend it along a smooth curve, like a banner",
  bulge: "Push the middle outward, like it's inflated",
  flag: "Ripple it side to side, like cloth in the wind",
  fisheye: "Magnify the centre, like a wide-angle lens",
};

// Evenly resample a polyline to N points along its length (closed loops wrap; open runs keep
// both ends fixed). flattenSubpaths only gives back the path's OWN vertices — a plain rectangle
// has just 4, all sitting exactly on this module's sine-based formulas' zero-crossings (x=0 and
// x=1), so without this every preset would render the rectangle completely unwarped: there is
// nothing BETWEEN the corners for a smooth deformation to act on.
function resample(pts, closed, N) {
  if (pts.length < 2) return pts.slice();
  const P = closed ? pts.concat([pts[0]]) : pts;
  const seg = []; let tot = 0;
  for (let i = 1; i < P.length; i++) { const L = Math.hypot(P[i].x - P[i - 1].x, P[i].y - P[i - 1].y); seg.push(L); tot += L; }
  if (tot < 1e-9) return pts.slice();
  const out = [], div = closed ? N : N - 1;
  for (let k = 0; k < N; k++) {
    const target = (k / div) * tot;
    let acc = 0, i = 0;
    while (i < seg.length && acc + seg[i] < target) { acc += seg[i]; i++; }
    if (i >= seg.length) { out.push({ x: P[P.length - 1].x, y: P[P.length - 1].y }); continue; }
    const u = seg[i] > 0 ? (target - acc) / seg[i] : 0;
    out.push({ x: P[i].x + (P[i + 1].x - P[i].x) * u, y: P[i].y + (P[i + 1].y - P[i].y) * u });
  }
  return out;
}
function warpXY(fn, x, y, bb, amount) {
  const w = (bb.x1 - bb.x0) || 1, h = (bb.y1 - bb.y0) || 1;
  const r = fn((x - bb.x0) / w, (y - bb.y0) / h, amount);
  return [bb.x0 + r.x * w, bb.y0 + r.y * h];
}
function warpPathD(d, fn, bb, amount) {
  const subs = flattenSubpaths(d, 0.4);
  const parts = [];
  for (const s of subs) {
    if (s.pts.length < 2) continue;
    const dense = resample(s.pts, s.closed, Math.max(80, Math.min(200, s.pts.length * 8)));
    const pts = dense.map((p) => warpXY(fn, p.x, p.y, bb, amount));
    if (s.closed) {
      const segs = fitLoop(pts, 0.6);
      if (segs.length) parts.push(cubicsToPath(segs));   // cubicsToPath already closes with Z
    } else {
      parts.push("M" + pts.map((p) => nfmt(p[0]) + " " + nfmt(p[1])).join(" L"));
    }
  }
  return parts.join(" ");
}

export const warpMixin = {
  isWarpGroup(n) { return !!(n && n.getAttribute && n.hasAttribute("data-hv-warp")); },
  _warpSpec(g) { try { return JSON.parse(g.getAttribute("data-hv-warp")); } catch { return null; } },
  _warpSet(g, spec) { g.setAttribute("data-hv-warp", JSON.stringify(spec)); },
  _warpGroupOf(n) { if (this.isWarpGroup(n)) return n; const g = n && n.closest && n.closest("[data-hv-warp]"); return g && this.stage && this.stage.contains(g) ? g : null; },
  // Rebuild the warp's children from its spec — same shape as blend's _regenBlend.
  _regenWarp(g) {
    const spec = this._warpSpec(g); if (!spec) return;
    const fn = WARP_FNS[spec.type]; if (!fn) return;
    [...g.children].forEach((c) => c.remove());
    for (const it of spec.items) {
      const d = warpPathD(it.d, fn, spec.bbox, spec.amount);
      if (!d) continue;
      const p = document.createElementNS(SVG_NS, "path");
      p.setAttribute("data-hv-id", "n" + (++this.idSeq));
      p.setAttribute("d", d);
      p.setAttribute("fill", it.fill);
      if (it.fillRule) p.setAttribute("fill-rule", it.fillRule);
      if (it.stroke && it.stroke !== "none") { p.setAttribute("stroke", it.stroke); if (it.sw != null) p.setAttribute("stroke-width", nfmt(it.sw)); }
      if (it.op != null) p.setAttribute("opacity", nfmt(it.op));
      if (it.fillOp != null) p.setAttribute("fill-opacity", nfmt(it.fillOp));
      g.appendChild(p);
    }
  },
  // Object > Warp > <preset>: warp the current selection as one group.
  makeWarp(type) {
    if (!this.stage || !WARP_FNS[type]) return;
    const sel = this._fillableSelection();
    if (!sel.length) { setStatus("Select one or more filled shapes to warp.", 3000); return; }
    const items = sel.map((n) => {
      const d = shapeToAbsPath(n, n.getCTM()); if (!d) return null;
      return {
        d, fill: n.getAttribute("fill") || "#000000", fillRule: n.getAttribute("fill-rule") || null,
        stroke: n.getAttribute("stroke") || null, sw: n.getAttribute("stroke-width") != null ? +n.getAttribute("stroke-width") : null,
        op: n.getAttribute("opacity") != null ? +n.getAttribute("opacity") : null, fillOp: n.getAttribute("fill-opacity") != null ? +n.getAttribute("fill-opacity") : null,
      };
    }).filter(Boolean);
    if (!items.length) { setStatus("None of the selection has a fillable outline to warp.", 3000); return; }
    const bb = this._bboxUnion(sel);
    this.push("Warp");
    const g = document.createElementNS(SVG_NS, "g");
    g.setAttribute("data-hv-id", "n" + (++this.idSeq));
    this._warpSet(g, { type, amount: 0.3, items, bbox: bb });
    const all = [...this.stage.querySelectorAll("[data-hv-id]")];
    sel.sort((a, b) => all.indexOf(a) - all.indexOf(b));
    const anchor = sel[sel.length - 1], parent = anchor.parentNode, ov = this._overlayEl();
    const ref = anchor.nextSibling;
    if (ref && ref.parentNode === parent && ref !== ov) parent.insertBefore(g, ref); else parent.appendChild(g);
    sel.forEach((n) => n.remove());
    this._regenWarp(g);
    this.selection = new Set([g.getAttribute("data-hv-id")]); this.artboardSelected = false;
    this._renderSelection(); this._renderInspector(); this._renderLayers();
    setStatus(`Warped with ${WARP_LABELS[type] || type}.`, 2000);
  },
  setWarpParam(g, key, value) {
    const spec = this._warpSpec(g); if (!spec) return;
    spec[key] = value; this._warpSet(g, spec); this._regenWarp(g); this._renderSelection();
  },
  expandWarp(g) {
    g = g || this.selectedNodes().map((n) => this._warpGroupOf(n)).find(Boolean);
    if (!this.isWarpGroup(g)) return;
    this.push("Expand warp");
    g.removeAttribute("data-hv-warp");
    this._renderSelection(); this._renderInspector(); this._renderLayers();
    setStatus("Warp expanded to a group.", 1800);
  },
};
